FROM dockerfile/java:oracle-java8

VOLUME /tmp
ADD cicd.jar /opt/cicd/
EXPOSE 8080
WORKDIR /opt/cicd/
CMD ["java", "-Djava.security.egd=file:/dev/./urandom", "-Xms512m", "-Xmx1g", "-jar", "cicd.jar"]
